version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - toll-network
    shm_size: '2gb'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  cache:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - toll-network

  test:
    image: nvidia/cuda:11.6.2-base-ubuntu20.04
    command: nvidia-smi
      # Remove deploy if not using Swarm
    networks:
      - toll-network
    # Add this for Compose v3.8+ to request all GPUs
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

networks:
  toll-network:
    driver: bridge

volumes:
  postgres_data:
